# Generated by Django 3.2 on 2022-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatBoysGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_participants', models.IntegerField(max_length=5)),
                ('level', models.CharField(max_length=15)),
                ('new_game', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
