# Generated by Django 3.2 on 2022-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batboysgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batboysgame',
            name='nb_participants',
            field=models.IntegerField(),
        ),
    ]
